apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: php
spec:
  selector:
    app: php
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

---
apiVersion: v1
kind: apiVersion: v1
kind: Service
metadata:
  name: mysql_connection
spec:
  ports:
    - port: 3306 
  selector:
    app: mysql_connection
  clusterIp:  None
